Repository opendilab/GoBigger, pull requests merged in 2021-11, with the labels that each got.

#4 fix SporeBall in step
  gobigger/server/server.py
Labels: bug

#5 Add test
  gobigger/agents/tests/test_base_agent.py
  gobigger/agents/tests/test_bot_agent.py
  gobigger/balls/tests/test_base_ball.py
  gobigger/balls/tests/test_clone_ball.py
  gobigger/balls/tests/test_food_ball.py
  gobigger/balls/tests/test_spore_ball.py
  gobigger/balls/tests/test_thorns_ball.py
  gobigger/managers/tests/test_base_manager.py
  gobigger/managers/tests/test_food_manager.py
  gobigger/managers/tests/test_player_manager.py
  gobigger/managers/tests/test_spore_manager.py
  gobigger/managers/tests/test_thorns_manager.py
  gobigger/players/human_player.py
  gobigger/players/tests/test_base_player.py
  gobigger/players/tests/test_human_player.py
  gobigger/render/env_render.py
  gobigger/render/test/test_env_render.py
  gobigger/utils/__init__.py
  gobigger/utils/precision_algorithm.py
  gobigger/utils/test/test_collision_detection.py
  gobigger/utils/tool.py
Labels: enhancement

#10 add advanced doc
  docs/en/source/advanced/cfg_intro.rst
  docs/en/source/advanced/collision.rst
  docs/en/source/advanced/custom_init.rst
  docs/en/source/advanced/images/changed_num_3000.png
  docs/en/source/advanced/images/iters_num_3000.png
  docs/en/source/advanced/images/query_num_3000.png
  docs/en/source/community/faq.rst
  docs/en/source/faq/index.rst
  docs/en/source/index.rst
  docs/en/source/tutorial/space.rst
  docs/zh_CN/source/advanced/cfg_intro.rst
  docs/zh_CN/source/advanced/collision.rst
  docs/zh_CN/source/advanced/custom_init.rst
  docs/zh_CN/source/advanced/images/changed_num_3000.png
  docs/zh_CN/source/advanced/images/iters_num_3000.png
  docs/zh_CN/source/advanced/images/query_num_3000.png
  docs/zh_CN/source/community/faq.rst
  docs/zh_CN/source/index.rst
  docs/zh_CN/source/tutorial/space.rst
Labels: documentation

#14 adjust ovs shape
  gobigger/agents/bot_agent.py
  gobigger/render/env_render.py
Labels: enhancement

#19 add space
  docs/zh_CN/source/tutorial/real_time_interaction_with_game.rst
Labels: documentation
